// <auto-generated />
using System;
using System.Collections.Generic;
using Checkiski.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Checkiski.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522172652_PhaseB_PhaseC_Updates")]
    partial class PhaseB_PhaseC_Updates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Checkiski.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("BlackClockRemaining")
                        .HasColumnType("interval");

                    b.Property<Guid?>("BlackPlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentFen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<string>>("MoveList")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("WhiteClockRemaining")
                        .HasColumnType("interval");

                    b.Property<Guid>("WhitePlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerId");

                    b.HasIndex("WhitePlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Checkiski.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlitzRating")
                        .HasColumnType("integer");

                    b.Property<int>("BulletRating")
                        .HasColumnType("integer");

                    b.Property<int>("ClassicalRating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RapidRating")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Checkiski.Domain.Entities.Game", b =>
                {
                    b.HasOne("Checkiski.Domain.Entities.Player", "BlackPlayer")
                        .WithMany("GamesAsBlack")
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Checkiski.Domain.Entities.Player", "WhitePlayer")
                        .WithMany("GamesAsWhite")
                        .HasForeignKey("WhitePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Checkiski.Domain.ValueObjects.GameOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ColorChoice")
                                .HasColumnType("integer")
                                .HasColumnName("Options_ColorChoice");

                            b1.Property<int>("GameCategory")
                                .HasColumnType("integer")
                                .HasColumnName("Options_GameCategory");

                            b1.Property<bool>("Rated")
                                .HasColumnType("boolean")
                                .HasColumnName("Options_Rated");

                            b1.HasKey("GameId");

                            b1.ToTable("Games");

                            b1.WithOwner()
                                .HasForeignKey("GameId");

                            b1.OwnsOne("Checkiski.Domain.ValueObjects.TimeControl", "TimeControl", b2 =>
                                {
                                    b2.Property<Guid>("GameOptionsGameId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("BaseMinutes")
                                        .HasColumnType("integer")
                                        .HasColumnName("Options_TimeControl_BaseMinutes");

                                    b2.Property<int>("IncrementSeconds")
                                        .HasColumnType("integer")
                                        .HasColumnName("Options_TimeControl_IncrementSeconds");

                                    b2.HasKey("GameOptionsGameId");

                                    b2.ToTable("Games");

                                    b2.WithOwner()
                                        .HasForeignKey("GameOptionsGameId");
                                });

                            b1.Navigation("TimeControl")
                                .IsRequired();
                        });

                    b.Navigation("BlackPlayer");

                    b.Navigation("Options")
                        .IsRequired();

                    b.Navigation("WhitePlayer");
                });

            modelBuilder.Entity("Checkiski.Domain.Entities.Player", b =>
                {
                    b.Navigation("GamesAsBlack");

                    b.Navigation("GamesAsWhite");
                });
#pragma warning restore 612, 618
        }
    }
}
